repository: "craigsapp/polyrhythm-web"

output: "web"
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: "polyrhythm"
# this appears on the top navigation bar next to the home button

site_title: "polyrhythm"
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)


# Sets the website to use local javascript/css only.
#local: "true"
local: "false"

company_name: "University of British Columbia"
# this appears in the footer

host: 127.0.0.1
# the preview server used. Leave as is.

port: 8888
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

production_url: http://polyrhythm.humdrum.org/
BASE_PATH: http://polyrhythm.humdrum.org/

# Location of CSS files and fonts.
css: style

# exclude: these are the files and directories that jekyll will 
# not copy into the compiled website.
exclude:
  - .idea/
  - .gitignore
  - resources/recordings/wav

# highlighter: library used for syntax highlighting
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways


